/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class AplikasiBukuAlamat extends javax.swing.JFrame {
   

    /**
     * Creates new form AplikasiBukuAlamat
     */
    public AplikasiBukuAlamat() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    
    public void  bersihkan (){
        tfId.setText("");
        tfnama.setText("");
        tfnotelp.setText("");
        tfalamat.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfnotelp = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealamat = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnekspor = new javax.swing.JButton();
        btnimport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btntambah.setBackground(new java.awt.Color(204, 204, 204));
        btntambah.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        tfId.setBackground(new java.awt.Color(204, 204, 204));
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Id");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("No.Telp");

        tfnama.setBackground(new java.awt.Color(204, 204, 204));

        tfnotelp.setBackground(new java.awt.Color(204, 204, 204));
        tfnotelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnotelpKeyTyped(evt);
            }
        });

        tfalamat.setBackground(new java.awt.Color(204, 204, 204));
        tfalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfalamatActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(204, 204, 204));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tablealamat.setBackground(new java.awt.Color(255, 204, 255));
        tablealamat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "No.Telp", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablealamat);

        btnsimpan.setBackground(new java.awt.Color(204, 204, 204));
        btnsimpan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnekspor.setBackground(new java.awt.Color(204, 204, 204));
        btnekspor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnekspor.setText("Ekspor");
        btnekspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneksporActionPerformed(evt);
            }
        });

        btnimport.setBackground(new java.awt.Color(204, 204, 204));
        btnimport.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnimport.setText("Import");
        btnimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnekspor)
                .addGap(35, 35, 35)
                .addComponent(btnimport)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btntambah)
                        .addGap(38, 38, 38)
                        .addComponent(btnedit)
                        .addGap(43, 43, 43)
                        .addComponent(btnsimpan)
                        .addGap(40, 40, 40)
                        .addComponent(btnhapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnekspor)
                    .addComponent(btnimport))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfalamatActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tablealamat.getModel();
        
        if (tfId.getText().equals("") ||
                tfnama.getText().equals("") ||
                tfnotelp.getText().equals("") ||
                tfalamat.getText().equals("")
                
                
                
            ) 
                 {
                     JOptionPane.showMessageDialog(null, "Text Field Tidak Boleh Kosong");   // notifikasi pesan pada saat Text Field tidak di isi
            
            
        }  
        else{
             List list = new ArrayList<>();
            tablealamat.setAutoCreateColumnsFromModel(true);
            list.add(tfId.getText());
            list.add(tfnama.getText());           
            list.add(tfnotelp.getText());
            list.add(tfalamat.getText());
            dataModel.addRow(list.toArray());
            
            bersihkan();
        
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");   // notifikasi pesan pada saat berhasil di tambah
        }
       
           
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tablealamat.getModel(); 
                       int[] row=  tablealamat.getSelectedRows(); 

                for (int x  = 0; x <row.length; x++) {
                    dataModel.removeRow(row[x]-x);
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");  // notifikasi pesan pada saat berhasil di hapus
                    
            }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tablealamat.getModel(); 
        int row=tablealamat.getSelectedRow();
        tfId.setText(tablealamat.getValueAt(row, 0).toString());
        tfnama.setText(tablealamat.getValueAt(row, 1).toString());
        tfnotelp.setText(tablealamat.getValueAt(row, 2).toString());
        tfalamat.setText(tablealamat.getValueAt(row, 3).toString());
        
        JOptionPane.showMessageDialog(null, "Apakah Anda Ingin Mengeditnya?");   // notifikasi pesan pada saat ingin mengedit
        
       
        
        
        
        
        
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tablealamat.getModel(); 
        int row=tablealamat.getSelectedRow();
        
        if ((row>=0)) {
            
        dataModel.setValueAt(tfId.getText(), row, 0);
        dataModel.setValueAt(tfnama.getText(), row, 1);
        dataModel.setValueAt(tfnotelp.getText(), row, 2);
        dataModel.setValueAt(tfalamat.getText(), row, 3);
       
        
        } 
        
        bersihkan();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");   // notifikasi pesan pada saat berhasil di simpan
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneksporActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tablealamat.getModel(); 
              

try (BufferedWriter bw = new BufferedWriter(new FileWriter(new File("C:\\Users\\ACER\\Documents\\NetBeansProjects\\NidaAmirah-2110010045-UTS\\Ekspor.txt")))) {
    //  data yang diekspor akan masuk ke dalam file txt //
    StringJoiner joiner = new StringJoiner(",");
    for (int col = 0; col < dataModel.getColumnCount(); col++) {
        joiner.add(dataModel.getColumnName(col));
    }
    System.out.println(joiner.toString());
    bw.write(joiner.toString());
    bw.newLine();
    for (int row = 0; row < dataModel.getRowCount(); row++) {
        joiner = new StringJoiner(",");
        for (int col = 0; col < dataModel.getColumnCount(); col++) {
            Object obj = dataModel.getValueAt(row, col);
            String value = obj == null ? "null" : obj.toString();
            joiner.add(value);
        }
        System.out.println(joiner.toString());
        bw.write(joiner.toString());
        bw.newLine();
    } 
     JOptionPane.showMessageDialog(null, "Data Berhasil Di Ekspor ");   // notifikasi pesan pada saat berhasil di ekspor
} catch (IOException exp) {
    exp.printStackTrace();
}
    }//GEN-LAST:event_btneksporActionPerformed

    private void btnimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimportActionPerformed
         String filePath = "C:\\Users\\ACER\\Documents\\NetBeansProjects\\NidaAmirah-2110010045-UTS\\Import.txt";
            // data yang ada di dalam file Import akan keluar otomatis apabila tombol Import di tekan saat running aplikasi  
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file); 
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tablealamat.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
                
            }
             JOptionPane.showMessageDialog(null, "Data Berhasil Di Import ");  // notifikasi pesan pada saat berhasil di import
            
            
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnimportActionPerformed

    private void tfnotelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnotelpKeyTyped
        // fungsinya hanya untuk menuliskan angka saja 
        char c = evt.getKeyChar();
        if (!     ((Character.isDigit(c)    ||
                   (c  == KeyEvent.VK_BACK_SPACE)  ||
                   (c == KeyEvent.VK_DELETE) 
                
                ))) {
        getToolkit() .beep();
        JOptionPane.showMessageDialog(null, "Masukan hanya 0-9!");   // notifikasi pesan pada saat salah mengetik 
        evt.consume();
        
        
        }
    }//GEN-LAST:event_tfnotelpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiBukuAlamat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnekspor;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnimport;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablealamat;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnotelp;
    // End of variables declaration//GEN-END:variables

    private FileWriter FileWriter(File fileSimpan) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
